/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fathan.main;

import com.fathan.db.configdb;
import java.awt.Color;
import java.sql.Connection;

/**
 *
 * @author Fathan
 */
public class forgotPassword extends javax.swing.JDialog {

    /**
     * Creates new form forgotPassword
     */
    public forgotPassword(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setBackground(new Color(0, 0, 0, 0));
        jLabel2.setVisible(false);
        jLabel6.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelShadow1 = new main.PanelShadow();
        jLabel1 = new javax.swing.JLabel();
        panelBordeer2 = new com.fathan.swing.PanelBordeer();
        field_username = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelShadow3 = new main.PanelShadow();
        jLabel4 = new javax.swing.JLabel();
        panelShadow2 = new main.PanelShadow();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(535, 260));
        setMinimumSize(new java.awt.Dimension(535, 260));
        setUndecorated(true);
        setOpacity(0.0F);
        setPreferredSize(new java.awt.Dimension(535, 260));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelShadow1.setBackground(new java.awt.Color(255, 255, 255));
        panelShadow1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(19, 179, 200));
        jLabel1.setText("Lupa Kata Sandi");
        panelShadow1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 280, 40));

        panelBordeer2.setBackground(new java.awt.Color(255, 255, 255));
        panelBordeer2.setForeground(new java.awt.Color(226, 226, 226));
        panelBordeer2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        field_username.setBackground(new java.awt.Color(226, 226, 226));
        field_username.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        field_username.setBorder(null);
        field_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_usernameActionPerformed(evt);
            }
        });
        field_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                field_usernameKeyTyped(evt);
            }
        });
        panelBordeer2.add(field_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 0, 430, 40));

        panelShadow1.add(panelBordeer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 460, 40));

        jLabel6.setFont(new java.awt.Font("Montserrat SemiBold", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 0));
        jLabel6.setText("Tunggu Konfirmasi dari Admin!");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelShadow1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 290, 20));

        jLabel2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Lupa Kata Sandi Berhasil Diajukan");
        panelShadow1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 290, 20));

        panelShadow3.setBackground(new java.awt.Color(255, 51, 51));
        panelShadow3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("BATAL");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        panelShadow3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        panelShadow1.add(panelShadow3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 90, 40));

        panelShadow2.setBackground(new java.awt.Color(255, 255, 255));
        panelShadow2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(19, 179, 200));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("KIRIM");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        panelShadow2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        panelShadow1.add(panelShadow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 90, 40));

        jLabel5.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel5.setText("Masukkan Nama Pengguna / Username yang anda gunakan");
        panelShadow1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 80, 380, 40));

        getContentPane().add(panelShadow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 260));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.0; i <= 1.0; i = i + 0.25) {
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try {
                Thread.sleep(2);
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void field_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_usernameActionPerformed

    private void field_usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_field_usernameKeyTyped
        if (field_username.isEditable()) {
            jLabel2.setVisible(false);
            jLabel6.setVisible(false);
        }
    }//GEN-LAST:event_field_usernameKeyTyped

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        for (double i = 1.0; i >= 0.1; i = i - 0.25) {
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try {
                Thread.sleep(1);
                if (this.getOpacity() <= 0.25) {
                    this.dispose();
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        String id_pengguna = null;
        if (field_username.getText().equals("")) {
            jLabel2.setVisible(true);
            jLabel2.setText("Nama Pengguna / Username Kosong!");
            jLabel2.setForeground(new Color(255, 51, 51));
            jLabel6.setVisible(false);
        } else {
            try {
                String sql = "SELECT * FROM pengguna WHERE nama_pengguna = '" + field_username.getText() + "';";
                java.sql.Connection con = (Connection) configdb.GetConnection();
                java.sql.Statement st = con.createStatement();
                java.sql.ResultSet rs = st.executeQuery(sql);
                if (rs.next()) {
                    id_pengguna = rs.getString("id_pengguna");
                }
                System.out.println("1. " + id_pengguna);
                if (id_pengguna == null) {
                    jLabel2.setVisible(true);
                    jLabel2.setText("Nama Pengguna / Username Tidak Terdaftar!");
                    jLabel2.setForeground(new Color(255, 51, 51));
                    jLabel6.setVisible(false);
                } else {
                    try {
                        String sql1 = "UPDATE pengguna SET status = 'lupa' WHERE id_pengguna = '" + id_pengguna + "';";
                        java.sql.Connection conn = (Connection) configdb.GetConnection();
                        java.sql.Statement stt = conn.createStatement();
                        stt.execute(sql1);
                        jLabel2.setVisible(true);
                        jLabel2.setText("Lupa Kata Sandi Berhasil Diajukan!!");
                        jLabel2.setForeground(Color.GREEN);
                        jLabel6.setVisible(true);
                        jLabel6.setForeground(Color.GREEN);
                        System.out.println("2. " + id_pengguna);
                        field_username.setText("");
                    } catch (Exception e) {
                        System.err.println(e.getMessage());
                    }
                }

            } catch (Exception e) {
                System.err.println(e.getMessage());
                jLabel2.setVisible(true);
                jLabel2.setText("Nama Pengguna / Username Tidak Ditemukan!!");
                jLabel2.setForeground(new Color(255, 51, 51));
                jLabel6.setVisible(false);
            }
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                forgotPassword dialog = new forgotPassword(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField field_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private com.fathan.swing.PanelBordeer panelBordeer2;
    private main.PanelShadow panelShadow1;
    private main.PanelShadow panelShadow2;
    private main.PanelShadow panelShadow3;
    // End of variables declaration//GEN-END:variables
}
