/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fathan.main;

import com.fathan.db.configdb;
import java.awt.Color;
import java.awt.Frame;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Date;

/**
 *
 * @author Fathan
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        this.setBackground(new Color(0, 0, 0, 0));
        label_salah.setVisible(false);
        label_salah1.setVisible(false);
        clear_log();
        new com.fathan.form.beranda.beranda().setVisible(false);
        System.out.println(new com.fathan.form.about.logout().getStatusLog_Out());
    }

    public void clear_log(){
        try {
            String sql = "DELETE FROM log_pengguna WHERE DATEDIFF(CURTIME(), log_pengguna.stamp) > 30";
            java.sql.Connection con = (Connection)configdb.GetConnection();
            java.sql.Statement st = con.createStatement();
            st.execute(sql);
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBordeer1 = new com.fathan.swing.PanelBordeer();
        label_salah1 = new javax.swing.JLabel();
        label_forgerpw = new javax.swing.JLabel();
        label_salah = new javax.swing.JLabel();
        button3 = new com.fathan.swing.Button();
        button2 = new com.fathan.swing.Button();
        jSeparator1 = new javax.swing.JSeparator();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        panelBordeer3 = new com.fathan.swing.PanelBordeer();
        field_password = new javax.swing.JPasswordField();
        panelBordeer2 = new com.fathan.swing.PanelBordeer();
        field_username = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1294, 679));
        setUndecorated(true);
        setOpacity(0.0F);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBordeer1.setForeground(new java.awt.Color(204, 204, 204));
        panelBordeer1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_salah1.setFont(new java.awt.Font("Montserrat Medium", 0, 11)); // NOI18N
        label_salah1.setForeground(new java.awt.Color(255, 0, 0));
        label_salah1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        label_salah1.setText("Gagal Masuk!");
        panelBordeer1.add(label_salah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 430, 150, 20));

        label_forgerpw.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        label_forgerpw.setForeground(new java.awt.Color(68, 185, 200));
        label_forgerpw.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        label_forgerpw.setText("Lupa Kata Sandi?");
        panelBordeer1.add(label_forgerpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(1018, 400, 140, 30));

        label_salah.setFont(new java.awt.Font("Montserrat Medium", 0, 11)); // NOI18N
        label_salah.setForeground(new java.awt.Color(255, 0, 0));
        label_salah.setText("Nama Pengguna / Kata Sandi salah!");
        panelBordeer1.add(label_salah, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, 210, 20));

        button3.setBackground(new java.awt.Color(157, 210, 217));
        button3.setForeground(new java.awt.Color(255, 255, 255));
        button3.setText("DAFTAR");
        button3.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        panelBordeer1.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 540, 380, 40));

        button2.setBackground(new java.awt.Color(82, 226, 245));
        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setText("MASUK");
        button2.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        panelBordeer1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 460, 380, 40));

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        panelBordeer1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 520, 320, 10));

        jCheckBox1.setBackground(new java.awt.Color(247, 247, 247));
        jCheckBox1.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jCheckBox1.setText("Lihat Kata Sandi");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        panelBordeer1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, 190, 30));

        jLabel5.setFont(new java.awt.Font("Montserrat Medium", 0, 13)); // NOI18N
        jLabel5.setText("Kata Sandi");
        panelBordeer1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 320, 210, 30));

        panelBordeer3.setBackground(new java.awt.Color(255, 255, 255));
        panelBordeer3.setForeground(new java.awt.Color(226, 226, 226));

        field_password.setBackground(new java.awt.Color(226, 226, 226));
        field_password.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        field_password.setBorder(null);
        field_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                field_passwordKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelBordeer3Layout = new javax.swing.GroupLayout(panelBordeer3);
        panelBordeer3.setLayout(panelBordeer3Layout);
        panelBordeer3Layout.setHorizontalGroup(
            panelBordeer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBordeer3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(field_password, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panelBordeer3Layout.setVerticalGroup(
            panelBordeer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(field_password, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        panelBordeer1.add(panelBordeer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 350, 380, 50));

        panelBordeer2.setBackground(new java.awt.Color(255, 255, 255));
        panelBordeer2.setForeground(new java.awt.Color(226, 226, 226));

        field_username.setBackground(new java.awt.Color(226, 226, 226));
        field_username.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        field_username.setBorder(null);
        field_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_usernameActionPerformed(evt);
            }
        });
        field_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                field_usernameKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelBordeer2Layout = new javax.swing.GroupLayout(panelBordeer2);
        panelBordeer2.setLayout(panelBordeer2Layout);
        panelBordeer2Layout.setHorizontalGroup(
            panelBordeer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBordeer2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(field_username, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        panelBordeer2Layout.setVerticalGroup(
            panelBordeer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(field_username, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        panelBordeer1.add(panelBordeer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 260, 380, 50));

        jLabel4.setFont(new java.awt.Font("Montserrat Medium", 0, 13)); // NOI18N
        jLabel4.setText("Nama Pengguna");
        panelBordeer1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 230, 210, 30));

        jLabel3.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Masukkan Nama Pengguna dan Kata Sandi");
        panelBordeer1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, 340, 20));

        jLabel2.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 34)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Selamat Datang");
        panelBordeer1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 130, 340, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fathan/main/bg_login.png"))); // NOI18N
        panelBordeer1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 680));

        getContentPane().add(panelBordeer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void field_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_usernameActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()) {
            field_password.setEchoChar((char) 0);
        } else {
            field_password.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    com.fathan.user.user usr = new com.fathan.user.user();

    public void login() {
        
        try {
            String sql = "SELECT * FROM `pengguna` WHERE nama_pengguna = '" + field_username.getText() + "' && kata_sandi = '" + field_password.getText() + "';";
            Connection con = (Connection) configdb.GetConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (rs.next()) {
                String sql2 = "SELECT * FROM `detail_pengguna` WHERE `id_pengguna` = '" + rs.getString("id_pengguna") + "'";
                Connection conn = (Connection) configdb.GetConnection();
                Statement stt = conn.createStatement();
                ResultSet rss = stt.executeQuery(sql2);
                usr.setNama(rs.getString("nama_pengguna"));
                usr.setRole(rs.getString("role"));
                usr.setId_pengguna(rs.getString("id_pengguna"));
                System.out.println("No. Pengguna : " + rs.getString("id_pengguna"));
                if (rs.getString("role").equals("admin")) {
                    label_salah.setVisible(true);
                    label_salah.setForeground(new Color(80, 235, 77));
                    label_salah.setText("Berhasil Masuk!");
                    if (rss.next()) {
                        System.out.println("Nama Lengkap : " + rss.getString("nama_lengkap"));
                        new com.fathan.form.beranda.beranda().label_ucapan.setText("Selamat Datang, "+rs.getString("nama_pengguna"));
                        new com.fathan.form.beranda.beranda().label_nama.setText(rss.getString("nama_lengkap"));
                        usr.setNama_Lengkap(rss.getString("nama_lengkap"));
                        try {
                            Date today = new Date();
                            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
                            String stampLoginAdmin = "INSERT INTO `log_pengguna`(`no_log`, `id_pengguna`, `nama_pengguna`, `role`, `stamp`, `tipe`) "
                                + "VALUES (NULL, '"+usr.getId_pengguna()+"','"+usr.getNama()+"','"+usr.getRole()+"','"+sdf.format(today)+"','Masuk')";
                            Connection con1 = (Connection)configdb.GetConnection();
                            Statement st1 = con1.createStatement();
                            st1.execute(stampLoginAdmin);
                            new com.fathan.form.beranda.beranda().setVisible(true);
                        } catch (Exception e) {
                            label_salah1.setVisible(true);
                            System.err.println(e.getMessage());
                        }
                    }
                    for (double i = 1.0; i >= 0.1; i = i - 0.25) {
                        String val = i + "";
                        float f = Float.valueOf(val);
                        this.setOpacity(f);
                        System.out.println(f);
                        try {
                            Thread.sleep(1);
                            if (this.getOpacity() <= 0.25) {
                                this.dispose();
                            }
                        } catch (Exception e) {
                        }

                    }
                } else if (rs.getString("hak_akses").equals("karyawan")) {
                    label_salah.setVisible(true);
                    label_salah.setForeground(new Color(80, 235, 77));
                    label_salah.setText("Berhasil Masuk!");
                }
            } else {
                label_salah.setVisible(true);
                label_salah.setForeground(new Color(255, 0, 0));
                label_salah.setText("Nama Pengguna / Kata Sandi salah!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Username Atau Katasandi Salah!!");
            System.err.println(e.getMessage());

        }
    }
    
    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        login();
    }//GEN-LAST:event_button2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.0; i <= 1.0; i = i + 0.25) {
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            System.out.println(f);
            try {
                Thread.sleep(2);
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        for (double i = 1.0; i >= 0.1; i = i - 0.25) {
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            System.out.println(f);
            try {
                Thread.sleep(1);
                if (this.getOpacity() <= 0.25) {
                    System.exit(0);
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_button3ActionPerformed

    private void field_usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_field_usernameKeyTyped
        if (field_username.isEditable()) {
            label_salah.setVisible(false);
        }
    }//GEN-LAST:event_field_usernameKeyTyped

    private void field_passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_field_passwordKeyTyped
        if (field_password.isEditable()) {
            label_salah.setVisible(false);
        }
    }//GEN-LAST:event_field_passwordKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.fathan.swing.Button button2;
    private com.fathan.swing.Button button3;
    private javax.swing.JPasswordField field_password;
    private javax.swing.JTextField field_username;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_forgerpw;
    private javax.swing.JLabel label_salah;
    private javax.swing.JLabel label_salah1;
    private com.fathan.swing.PanelBordeer panelBordeer1;
    private com.fathan.swing.PanelBordeer panelBordeer2;
    private com.fathan.swing.PanelBordeer panelBordeer3;
    // End of variables declaration//GEN-END:variables
}
