/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fathan.form.about.ubahAkun;

import com.fathan.form.about.*;
import com.fathan.db.configdb;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Fathan
 */
public class ubah_Katasandi extends javax.swing.JDialog {

    /**
     * @return the pwbaru
     */
    public boolean isPwbaru() {
        return pwbaru;
    }

    /**
     * @param pwbaru the pwbaru to set
     */
    public void setPwbaru(boolean pwbaru) {
        this.pwbaru = pwbaru;
    }

    /**
     * @return the konfirmasiPW
     */
    public boolean isKonfirmasiPW() {
        return konfirmasiPW;
    }

    /**
     * @param konfirmasiPW the konfirmasiPW to set
     */
    public void setKonfirmasiPW(boolean konfirmasiPW) {
        this.konfirmasiPW = konfirmasiPW;
    }

    /**
     * @return the pwlama
     */
    public boolean isPwlama() {
        return pwlama;
    }

    /**
     * @param pwlama the pwlama to set
     */
    public void setPwlama(boolean pwlama) {
        this.pwlama = pwlama;
    }

    /**
     * Creates new form lainnya
     */
    public ubah_Katasandi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setBackground(new Color(0, 0, 0, 0));
        check1.setVisible(false);
        check2.setVisible(false);
        check3.setVisible(false);
        label_warning.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelShadow1 = new main.PanelShadow();
        jLabel7 = new javax.swing.JLabel();
        panelBordeer7 = new com.fathan.swing.PanelBordeer();
        field_konfirmasibaru = new javax.swing.JPasswordField();
        jCheckBoxCustom1 = new com.fathan.swing.checkbox.JCheckBoxCustom();
        panelShadow3 = new main.PanelShadow();
        button3 = new com.fathan.form.about.Button();
        label_warning = new javax.swing.JLabel();
        panelBordeer6 = new com.fathan.swing.PanelBordeer();
        field_pwbaru = new javax.swing.JPasswordField();
        jCheckBoxCustom3 = new com.fathan.swing.checkbox.JCheckBoxCustom();
        panelShadow2 = new main.PanelShadow();
        button2 = new com.fathan.form.about.Button();
        jLabel2 = new javax.swing.JLabel();
        panelBordeer5 = new com.fathan.swing.PanelBordeer();
        field_pwlama = new javax.swing.JPasswordField();
        jCheckBoxCustom2 = new com.fathan.swing.checkbox.JCheckBoxCustom();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        check3 = new javax.swing.JLabel();
        check2 = new javax.swing.JLabel();
        check1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.0F);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelShadow1.setBackground(new java.awt.Color(255, 255, 255));
        panelShadow1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel7.setText("Konfirmasi Kata Sandi Baru");
        panelShadow1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 170, 30));

        panelBordeer7.setBackground(new java.awt.Color(255, 255, 255));
        panelBordeer7.setForeground(new java.awt.Color(226, 226, 226));
        panelBordeer7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        field_konfirmasibaru.setBackground(new java.awt.Color(226, 226, 226));
        field_konfirmasibaru.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        field_konfirmasibaru.setText("jPasswordField1");
        field_konfirmasibaru.setBorder(null);
        field_konfirmasibaru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                field_konfirmasibaruKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                field_konfirmasibaruKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                field_konfirmasibaruKeyTyped(evt);
            }
        });
        panelBordeer7.add(field_konfirmasibaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 320, 40));

        jCheckBoxCustom1.setBackground(new java.awt.Color(19, 179, 200));
        jCheckBoxCustom1.setIconTextGap(20);
        jCheckBoxCustom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCustom1ActionPerformed(evt);
            }
        });
        panelBordeer7.add(jCheckBoxCustom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 20, 20));

        panelShadow1.add(panelBordeer7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 400, 40));

        panelShadow3.setBackground(new java.awt.Color(255, 255, 255));
        panelShadow3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button3.setForeground(new java.awt.Color(19, 179, 200));
        button3.setText("BATAL");
        button3.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 13)); // NOI18N
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        panelShadow3.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        panelShadow1.add(panelShadow3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 120, 50));

        label_warning.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 12)); // NOI18N
        label_warning.setForeground(new java.awt.Color(255, 51, 51));
        label_warning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_warning.setText("Kata Sandi Lama Tidak Cocok !");
        panelShadow1.add(label_warning, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 250, 30));

        panelBordeer6.setBackground(new java.awt.Color(255, 255, 255));
        panelBordeer6.setForeground(new java.awt.Color(226, 226, 226));
        panelBordeer6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        field_pwbaru.setBackground(new java.awt.Color(226, 226, 226));
        field_pwbaru.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        field_pwbaru.setText("jPasswordField1");
        field_pwbaru.setBorder(null);
        field_pwbaru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                field_pwbaruKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                field_pwbaruKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                field_pwbaruKeyTyped(evt);
            }
        });
        panelBordeer6.add(field_pwbaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 320, 40));

        jCheckBoxCustom3.setBackground(new java.awt.Color(19, 179, 200));
        jCheckBoxCustom3.setIconTextGap(20);
        jCheckBoxCustom3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCustom3ActionPerformed(evt);
            }
        });
        panelBordeer6.add(jCheckBoxCustom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 20, 20));

        panelShadow1.add(panelBordeer6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 400, 40));

        panelShadow2.setBackground(new java.awt.Color(19, 179, 200));
        panelShadow2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button2.setBackground(new java.awt.Color(19, 179, 200));
        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setText("SIMPAN");
        button2.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 13)); // NOI18N
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        panelShadow2.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        panelShadow1.add(panelShadow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 120, 50));

        jLabel2.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Ubah Kata Sandi");
        panelShadow1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 390, 50));

        panelBordeer5.setBackground(new java.awt.Color(255, 255, 255));
        panelBordeer5.setForeground(new java.awt.Color(226, 226, 226));
        panelBordeer5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        field_pwlama.setBackground(new java.awt.Color(226, 226, 226));
        field_pwlama.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        field_pwlama.setText("jPasswordField1");
        field_pwlama.setBorder(null);
        field_pwlama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                field_pwlamaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                field_pwlamaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                field_pwlamaKeyTyped(evt);
            }
        });
        panelBordeer5.add(field_pwlama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 320, 40));

        jCheckBoxCustom2.setBackground(new java.awt.Color(19, 179, 200));
        jCheckBoxCustom2.setIconTextGap(20);
        jCheckBoxCustom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCustom2ActionPerformed(evt);
            }
        });
        panelBordeer5.add(jCheckBoxCustom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 20, 20));

        panelShadow1.add(panelBordeer5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 400, 40));

        jLabel5.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel5.setText("Masukkan Kata Sandi Lama");
        panelShadow1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 170, 30));

        jLabel8.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel8.setText("Masukkan Kata Sandi Baru");
        panelShadow1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 170, 30));

        check3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        check3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fathan/form/about/ubahAkun/check.png"))); // NOI18N
        panelShadow1.add(check3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 40, 40));

        check2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        check2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fathan/form/about/ubahAkun/check.png"))); // NOI18N
        panelShadow1.add(check2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 40, 40));

        check1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        check1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fathan/form/about/ubahAkun/check.png"))); // NOI18N
        panelShadow1.add(check1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 40, 40));

        getContentPane().add(panelShadow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.0; i <= 1.0; i = i + 0.25) {
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try {
                Thread.sleep(1);
            } catch (Exception e) {
                System.err.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_formWindowOpened

    com.fathan.user.user usr = new com.fathan.user.user();
    private boolean pwlama, pwbaru, konfirmasiPW;

    public void checkKataSandi(String key) {
        try {
            String sql = "SELECT pengguna.kata_sandi FROM pengguna WHERE pengguna.nama_pengguna = '" + usr.getNama() + "'";
            java.sql.Connection con = (Connection) configdb.GetConnection();
            java.sql.Statement st = con.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);
            if (rs.next()) {
                if (rs.getString("kata_sandi").equals(key)) {
                    check1.setVisible(true);
                    setPwlama(true);
                } else {
                    check1.setVisible(false);
                    setPwlama(false);
                }
            }
        } catch (Exception e) {
            System.err.println("checkKataSandi(271) : " + e.getMessage());
        }
    }

    public void stampUbahKataSandi() {
        try {
            String sql = "SELECT * FROM `pengguna` WHERE nama_pengguna = '" + usr.getNama() + "';";
            Connection con = (Connection) configdb.GetConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (rs.next()) {
                if (rs.getString("role").equals("admin")) {
                    try {
                        Date today = new Date();
                        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
                        String stampLoginAdmin = "INSERT INTO `log_pengguna`(`no_log`, `id_pengguna`, `nama_pengguna`, `role`, `stamp`, `tipe`) "
                                + "VALUES (NULL, '" + usr.getId_pengguna() + "','" + usr.getNama() + "','" + usr.getRole() + "','" + sdf.format(today) + "','Ubah Kata Sandi')";
                        Connection con1 = (Connection) configdb.GetConnection();
                        Statement st1 = con1.createStatement();
                        st1.execute(stampLoginAdmin);
                    } catch (Exception e) {
                        System.err.println(e.getMessage());
                    }
                } else if (rs.getString("role").equals("karyawan")) {
                    try {
                        Date today = new Date();
                        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
                        String stampLoginAdmin = "INSERT INTO `log_pengguna`(`no_log`, `id_pengguna`, `nama_pengguna`, `role`, `stamp`, `tipe`) "
                                + "VALUES (NULL, '" + usr.getId_pengguna() + "','" + usr.getNama() + "','" + usr.getRole() + "','" + sdf.format(today) + "','Ubah Kata Sandi')";
                        Connection con1 = (Connection) configdb.GetConnection();
                        Statement st1 = con1.createStatement();
                        st1.execute(stampLoginAdmin);
                    } catch (Exception e) {
                        System.err.println(e.getMessage());
                    }
                }
            }
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }

    }
    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        if (isPwlama() == false) {
            label_warning.setVisible(true);
            label_warning.setText("Kata Sandi Lama tidak Cocok");
            label_warning.setForeground(new Color(255, 51, 51));
        } else if (isPwbaru() == false) {
            label_warning.setVisible(true);
            label_warning.setText("Kata Sandi Baru kurang");
            label_warning.setForeground(new Color(255, 51, 51));
        } else if (isKonfirmasiPW() == false) {
            label_warning.setVisible(true);
            label_warning.setText("Konfirmasi Kata Sandi tidak cocok");
            label_warning.setForeground(new Color(255, 51, 51));
        } else {
            try {
                String sql = "UPDATE pengguna SET pengguna.kata_sandi = '" + field_konfirmasibaru.getText() + "' "
                        + "WHERE pengguna.id_pengguna = '" + usr.getId_pengguna() + "'";
                System.out.println(sql);
                java.sql.Connection con = (Connection) configdb.GetConnection();
                java.sql.PreparedStatement pst = con.prepareStatement(sql);
                pst.execute();
                label_warning.setVisible(true);
                label_warning.setText("Berhasil Ubah Kata Sandi!");
                label_warning.setForeground(new Color(51, 255, 51));
                setPwbaru(false);
                setPwlama(false);
                setKonfirmasiPW(false);
            } catch (Exception e) {
                System.err.println("Ubah Kata Sandi : " + e.getMessage());
            }
        }
        stampUbahKataSandi();
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        for (double i = 1.0; i >= 0.1; i = i - 0.25) {
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try {
                Thread.sleep(1);
                if (this.getOpacity() <= 0.25) {
                    this.dispose();
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_button3ActionPerformed

    private void field_pwlamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_field_pwlamaKeyPressed
        if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_V) {
            System.out.println("Disabled");
            evt.consume();
        }
    }//GEN-LAST:event_field_pwlamaKeyPressed

    private void field_pwbaruKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_field_pwbaruKeyPressed
        if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_V) {
            System.out.println("Disabled");
            evt.consume();
        }

    }//GEN-LAST:event_field_pwbaruKeyPressed

    private void field_konfirmasibaruKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_field_konfirmasibaruKeyPressed
        if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_V) {
            System.out.println("Disabled");
            evt.consume();
        }
        if (field_konfirmasibaru.getText().equals("")) {
            setKonfirmasiPW(false);
        }
    }//GEN-LAST:event_field_konfirmasibaruKeyPressed

    private void field_pwlamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_field_pwlamaKeyTyped
        if (field_pwlama.getText().length() > 30) {
            evt.consume();
        }
    }//GEN-LAST:event_field_pwlamaKeyTyped

    private void field_pwbaruKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_field_pwbaruKeyTyped
        if (field_pwbaru.getText().length() > 30) {
            evt.consume();
        }


    }//GEN-LAST:event_field_pwbaruKeyTyped

    private void field_konfirmasibaruKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_field_konfirmasibaruKeyTyped
        if (field_konfirmasibaru.getText().length() > 30) {
            evt.consume();
        }
        if (field_konfirmasibaru.getText().equals("")) {
            setKonfirmasiPW(false);
            check3.setVisible(false);
        }

    }//GEN-LAST:event_field_konfirmasibaruKeyTyped

    private void jCheckBoxCustom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCustom2ActionPerformed
        if (jCheckBoxCustom2.isSelected()) {
            field_pwlama.setEchoChar((char) 0);
        } else {
            field_pwlama.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBoxCustom2ActionPerformed

    private void jCheckBoxCustom3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCustom3ActionPerformed
        if (jCheckBoxCustom3.isSelected()) {
            field_pwbaru.setEchoChar((char) 0);
        } else {
            field_pwbaru.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBoxCustom3ActionPerformed

    private void jCheckBoxCustom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCustom1ActionPerformed
        if (jCheckBoxCustom1.isSelected()) {
            field_konfirmasibaru.setEchoChar((char) 0);
        } else {
            field_konfirmasibaru.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBoxCustom1ActionPerformed

    private void field_pwlamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_field_pwlamaKeyReleased
        String key = field_pwlama.getText();
        if (key != "") {
            checkKataSandi(key);
        } else {
            System.out.println("No Kata Sandi Matches");
            check1.setVisible(false);
        }
    }//GEN-LAST:event_field_pwlamaKeyReleased

    private void field_pwbaruKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_field_pwbaruKeyReleased
        if (!(field_pwbaru.getText().length() < 8)) {
            check2.setVisible(true);
            setPwbaru(true);
        } else {
            check2.setVisible(false);
            setPwbaru(false);
        }
    }//GEN-LAST:event_field_pwbaruKeyReleased

    private void field_konfirmasibaruKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_field_konfirmasibaruKeyReleased
        if (field_konfirmasibaru.getText().equals("")) {
            setKonfirmasiPW(false);
            check3.setVisible(false);
        } else if (field_konfirmasibaru.getText().length() < 8) {
            setKonfirmasiPW(false);
            check3.setVisible(false);
        } else if (field_konfirmasibaru.getText().equals(field_pwbaru.getText())) {
            check3.setVisible(true);
            setKonfirmasiPW(true);
        } else {
            check3.setVisible(false);
            setKonfirmasiPW(false);
        }
    }//GEN-LAST:event_field_konfirmasibaruKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ubah_Katasandi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ubah_Katasandi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ubah_Katasandi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ubah_Katasandi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ubah_Katasandi dialog = new ubah_Katasandi(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.fathan.form.about.Button button2;
    private com.fathan.form.about.Button button3;
    private javax.swing.JLabel check1;
    private javax.swing.JLabel check2;
    private javax.swing.JLabel check3;
    private javax.swing.JPasswordField field_konfirmasibaru;
    private javax.swing.JPasswordField field_pwbaru;
    private javax.swing.JPasswordField field_pwlama;
    private com.fathan.swing.checkbox.JCheckBoxCustom jCheckBoxCustom1;
    private com.fathan.swing.checkbox.JCheckBoxCustom jCheckBoxCustom2;
    private com.fathan.swing.checkbox.JCheckBoxCustom jCheckBoxCustom3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel label_warning;
    private com.fathan.swing.PanelBordeer panelBordeer5;
    private com.fathan.swing.PanelBordeer panelBordeer6;
    private com.fathan.swing.PanelBordeer panelBordeer7;
    private main.PanelShadow panelShadow1;
    private main.PanelShadow panelShadow2;
    private main.PanelShadow panelShadow3;
    // End of variables declaration//GEN-END:variables
}
