/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fathan.form.laporan;

import com.fathan.chart.ModelChart;
import com.fathan.db.configdb;
import com.fathan.swing.jtable.ScrollBarCustom;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.ImageObserver;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Fathan
 */
public class laporan extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    com.fathan.user.user usr = new com.fathan.user.user();

    public laporan() {
        initComponents();
        this.setBackground(new Color(0, 0, 0, 0));
        panel_top.setBackground(new Color(255, 255, 255, 240));
        panel_top1.setBackground(new Color(255, 255, 255, 100));
        scroll.setVerticalScrollBar(new com.fathan.swing.scrollbar.ScrollBarCustom());
        
        getDataBulanan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBordeer1 = new com.fathan.swing.PanelBordeer();
        panel_top1 = new com.fathan.swing.PanelRound();
        scroll = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        label_ucapan2 = new javax.swing.JLabel();
        chart2 = new com.fathan.chart.Chart();
        chart1 = new com.fathan.chart.Chart();
        label_ucapan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panel_top = new com.fathan.swing.PanelRound();
        button4 = new com.fathan.form.kategori.Button();
        label_ucapan1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1294, 679));
        setUndecorated(true);
        setOpacity(0.0F);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBordeer1.setForeground(new java.awt.Color(247, 247, 247));
        panelBordeer1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_top1.setBackground(new java.awt.Color(255, 255, 255));
        panel_top1.setRoundBottomLeft(15);
        panel_top1.setRoundBottomRight(15);
        panel_top1.setRoundTopLeft(15);
        panel_top1.setRoundTopRight(15);
        panel_top1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_top1MouseClicked(evt);
            }
        });
        panel_top1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scroll.setBackground(new java.awt.Color(255, 255, 255));
        scroll.setBorder(null);
        scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_ucapan2.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 22)); // NOI18N
        label_ucapan2.setForeground(new java.awt.Color(107, 107, 107));
        label_ucapan2.setText("Grafik Penjualan Harian");
        jPanel1.add(label_ucapan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 475, 70));
        jPanel1.add(chart2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 1110, 280));
        jPanel1.add(chart1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 1110, 280));

        label_ucapan.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 22)); // NOI18N
        label_ucapan.setForeground(new java.awt.Color(107, 107, 107));
        label_ucapan.setText("Grafik Penjualan Harian");
        jPanel1.add(label_ucapan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 475, 70));

        scroll.setViewportView(jPanel1);

        panel_top1.add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1200, 470));

        panelBordeer1.add(panel_top1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 1220, 490));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fathan/form/beranda/bg_beranda.png"))); // NOI18N
        panelBordeer1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, 440));

        panel_top.setBackground(new java.awt.Color(255, 255, 255));
        panel_top.setRoundBottomLeft(15);
        panel_top.setRoundBottomRight(15);
        panel_top.setRoundTopLeft(15);
        panel_top.setRoundTopRight(15);
        panel_top.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_topMouseClicked(evt);
            }
        });
        panel_top.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fathan/form/kategori/back.png"))); // NOI18N
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        panel_top.add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 70));

        label_ucapan1.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 22)); // NOI18N
        label_ucapan1.setForeground(new java.awt.Color(107, 107, 107));
        label_ucapan1.setText("Laporan");
        panel_top.add(label_ucapan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 475, 70));

        panelBordeer1.add(panel_top, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 1220, 70));

        getContentPane().add(panelBordeer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.0; i <= 1.0; i = i + 0.25) {
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            System.out.println(f);
            try {
                Thread.sleep(1);
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_formWindowOpened
    public void getDataBulanan() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyyMM");
        chart1.addLegend("Tanggal", new Color(245, 189, 135));
        Date a = new Date();
        String sql = "SELECT CAST(tgl_transaksi AS DATE) Tanggal, SUM(jual.total_harga) AS TotalPenjualan FROM jual\n"
                + "WHERE EXTRACT(YEAR_MONTH FROM tgl_transaksi) = '" + sdf.format(a) + "'\n"
                + "GROUP BY CAST(tgl_transaksi AS DATE)";
        try {
            java.sql.Connection con = (Connection) configdb.GetConnection();
            java.sql.Statement st = con.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                String tanggal = rs.getString(1);
                int total = rs.getInt(2);
                chart1.addData(new ModelChart(tanggal, new double[]{total}));
            }
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }

    @Override
    public int checkImage(Image image, ImageObserver observer) {
        return super.checkImage(image, observer); //To change body of generated methods, choose Tools | Templates.
    }

    private void panel_topMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_topMouseClicked

    }//GEN-LAST:event_panel_topMouseClicked

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        for (double i = 1.0; i >= 0.1; i = i - 0.25) {
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try {
                Thread.sleep(1);
                if (this.getOpacity() <= 0.25) {
                    this.dispose();
                }
            } catch (Exception e) {
            }
        }
        new com.fathan.form.beranda.beranda().setVisible(true);
    }//GEN-LAST:event_button4ActionPerformed

    private void panel_top1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_top1MouseClicked

    }//GEN-LAST:event_panel_top1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.fathan.form.kategori.Button button4;
    private com.fathan.chart.Chart chart1;
    private com.fathan.chart.Chart chart2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel label_ucapan;
    public javax.swing.JLabel label_ucapan1;
    public javax.swing.JLabel label_ucapan2;
    private com.fathan.swing.PanelBordeer panelBordeer1;
    private com.fathan.swing.PanelRound panel_top;
    private com.fathan.swing.PanelRound panel_top1;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables
}
